name: Build and Deploy Docker Image
on: [push]
jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token: ${{ secrets.DOCKER }}
        image-name: image
        dockerfile: Dockerfile
